name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      
      - name: Setup git-repo
        run: |
          curl https://storage.googleapis.com/git-repo-downloads/repo > repo
          chmod a+x repo
          
      - name: Sync sources
        run: |
          ./repo init -u https://github.com/mbober1/beaver-os-radxa
          ./repo sync -j$(nproc)
